// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xeuxubahcvyeebvgyulz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhldXh1YmFoY3Z5ZWVidmd5dWx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg4MjA2NTAsImV4cCI6MjA4NDM5NjY1MH0.H2TDuObf4P8mgHMpDXZSmbF_whVOhvaGg0dRGFcFTFs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});