// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zgbljyrrpvsgdztvaktg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpnYmxqeXJycHZzZ2R6dHZha3RnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MjA5NTQsImV4cCI6MjA2MDE5Njk1NH0.b-N3KkYSg66fxR9kv9zLtFsw4mE6nM_51lXv-2D1Dyc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);